### ISSUE TITLE
Don't report NQ as under of HQ items

### ISSUE THREAD

**Issue by DarthNerdus** [Critical-Impact/AllaganMarket#1]
First off, this is great! I'm really looking forward to the public release!

I have the first enhancement request for you: add configuration about NQ/HQ items. Right now, I'm getting undercut alerts for HQ items (raid foods) that are being undercut by 1 or 2 NQ listings. It would be great to have the option of only alerting on undercuts of the same quality level I'm posting at.

Thanks!

**Comment by alyssadev** [comment]
![image](https://github.com/user-attachments/assets/8439c8b1-5e76-4438-876f-2fca1189a990)

I'm experiencing this as well, on 1.0.0.1. Ideally this would ignore the NQ items as they're not undercutting.

**Comment by Critical-Impact** [comment]
This should now be possible on the latest testing version. There is an option to set it globally to these
Allow any
Match quality
Always NQ
Always HQ

This option to override the global setting is available on a item level as well(right click on the item in grid mode). I forgot to add the same right click options to list mode but I'll fix that in the next release.

**Comment by DarthNerdus** [comment]
This is great, thanks so much for addressing this so quickly!
