### ISSUE TITLE
[BUG] Highlighting highlights the wrong items

### ISSUE THREAD

**Issue by SuspiciousActivity** [Critical-Impact/AllaganMarket#12]
**Describe the bug**
Sometimes the highlighting highlights the wrong items in the sell list.

**To Reproduce**
I'm not sure what causes this, but I was able to reproduce it using this:
1. Sell a Snow Linen and a Bright Linen Yarn in an empty retainer like this:
2. Snow Linen at a high price (for example 999.999)
3. Bright Linen Yarn at a low price (for example the recommended price or lower)
4. Snow Linen *should* be highlighted, but instead the Bright Linen Yarn is highlighted (wrong)

**Expected behavior**
Correct items should be highlighted.

**Screenshots**
A screenshot of my try to reproduce it minimally:
![grafik](https://github.com/user-attachments/assets/f983e3db-a44e-4960-a0b3-5298e7ff2263)

Screenshots where I originally encountered the bug:
This seems to mainly happen when you have the same item type twice in your sell list.
For example, here I have two orchestrion rolls, the upper one has been undercut (shows correctly on the right panel), but the item below gets highlighted:
![grafik](https://github.com/user-attachments/assets/549dfbea-4608-4339-8bb7-7ca5c6b906c6)

In the second example, I have a NQ and HQ Blue Zircon, both have been undercut (correct on the right), the first one is highlighted but the second one isn't, and instead the Annite Whetstone below (which is NOT undercut) is highlighted.
Then I have two different metals which have been undercut and show correctly, and two different clothes, where the Snow Linen has been undercut but is again NOT highlighted, the item below it is highlighted instead:
![grafik](https://github.com/user-attachments/assets/970160e1-2506-4640-968e-27b80e7dd9f1)

**Comment by Critical-Impact** [comment]
Fixed in latest version
