### ISSUE TITLE
Chat messages still being shown when disabled

### ISSUE THREAD

**Issue by alyssadev** [Critical-Impact/AllaganMarket#4]
![image](https://github.com/user-attachments/assets/808dc0d8-45be-4594-acee-c1378ac8424a)

I imagine the options shown prevent chat notifications when the price update task completes, but IMO it should also block these undercut messages. At the very least the chat channel for these messages should be configurable or sent to Echo.

**Comment by alyssadev** [comment]
![image](https://github.com/user-attachments/assets/4a5d8d08-c0f6-4ab6-bdc2-f65f8c4b11ea)
Showing these notifications for each and every price list open as I'm updating a bunch of small tincture stacks is absurd tbh

**Comment by Critical-Impact** [comment]
I'm making some changes that'll allow for these messages to be configured/grouped together to reduce the spam.

Might not be until the weekend till I get a chance to get a new build out but thanks for the post :)

**Comment by Critical-Impact** [comment]
Please give this a go on the latest version, if you run into issues please reopen a new ticket :)
