### ISSUE TITLE
List sorting

### ISSUE THREAD

**Issue by MikevLeeuwen** [Critical-Impact/AllaganMarket#5]
The list doesn't seem to be able to be sorted correctly. This is the case for all columns.

![list sorting 2](https://github.com/user-attachments/assets/909ed389-6345-46ae-85dc-9ed312bdad9b)
List sorting by "Unit Price"
<br>

![list sorting 1](https://github.com/user-attachments/assets/0333bf32-9030-4b10-8b2c-d32403d91c72)
List sorting by "Undercut by"

**Comment by Critical-Impact** [comment]
Should be fixed in the latest testing release, the next release will also add in number formatting and the gil symbol for currency columns
