### ISSUE TITLE
[BUG] Undercut warning for HQ item without HQ items being on marketboard

### ISSUE THREAD

**Issue by MikevLeeuwen** [Critical-Impact/AllaganMarket#8]
The plugin shows an undercut warning of a HQ item if a NQ item is on the marketboard without a HQ item being there. 
This seems to only be the case if a NQ item is on the marketboard though. If only HQ items, or no items exist, it seems to work as intended.

![undercut warning on item](https://github.com/user-attachments/assets/4d5d986c-d2d4-4bba-813b-3f39ae1f8e91)

![Item list on marketboard](https://github.com/user-attachments/assets/c9908aff-38f6-4a23-971a-50d77704578a)

**Comment by Critical-Impact** [comment]
Out of curiosity, what is your "Undercut comparison" setting configured to?

**Comment by MikevLeeuwen** [comment]
It's set to "Matches Quality"

**Comment by Critical-Impact** [comment]
Thanks, while I can't say for sure this'll fix the issue your seeing, the new version will have a fix that will evalulate the offerings received from both the game and universalis on the whole and if there is no NQ or HQ listing available, it'll attempt to remove the old listing which should stop it being counted towards any undercut checks.

**Comment by Juniaurie** [comment]
Hi! I just started using this and it's happening for me as well. I've tried all the different settings and it doesn't seem to make a difference. Will the new version be coming out soon? Thanks so much for making this!

**Comment by Juniaurie** [comment]
Oh, also, sorry for the double post, but I just thought of something to add. I've noticed that the recommended price is accurate to the quality level. It's just the red highlighting that's not syncing. For instance I'm selling HQ Omelette Rice. My original price was 5,750, but the lowest HQ currently for sale is 5,733. The Rec. Price listed is 5,728, which would be 5 less than the lowest HQ price, but when I change it to that amount, the red highlight stays. I'm attaching a screenshot just in case it helps.

![AM Example](https://github.com/user-attachments/assets/0b46983a-08da-43bf-8323-75b38d3280bd)
