### ISSUE TITLE
Add Open Crafting Log option to Sale History tab

### ISSUE THREAD

**Issue by nightpanda2810** [Critical-Impact/AllaganMarket#9]
**Is your feature request related to a problem? Please describe.**
Most of what I sell I craft, and its a rather tedious task to gather the data of my sales, find the item in my crafting list, and go about my crafting. Would be fantastic to have this option directly in the plugin to streamline my crafting workflow.

**Describe the solution you'd like**
Add the option "Open Crafting List" to the right-click menu in the sale history tab. 

**Additional context**
Thank you for this amazing plugin! It's already greatly improved things for me.

**Comment by Critical-Impact** [comment]
Added to latest version
